version: "3"

services:
  nonebot:
    build: .
    ports:
      - "8080:8080"

    env_file:
      - .env.prod

    volumes:
      - ./assets:/app/assets

    environment:
      ENVIRONMENT: prod
      HOST: 0.0.0.0
      PORT: 8080

      HTTP_PROXY: http://mihomo:7890
      HTTPS_PROXY: http://mihomo:7890
      ALL_PROXY: socks5://mihomo:7890

      http_proxy: http://mihomo:7890
      https_proxy: http://mihomo:7890
      all_proxy: socks5://mihomo:7890

      NO_PROXY: localhost,127.0.0.1,mihomo,flaresolverr,172.18.0.1
      no_proxy: localhost,127.0.0.1,mihomo,flaresolverr,172.18.0.1

      FLARESOLVERR_URL: http://flaresolverr:8191/v1


    networks:
      - default
      - proxy-net

    restart: always

networks:
  proxy-net:
    external: true